_target_: agents.rl.sac_ensemble.SACEnsemble
ensemble_size: 5
device: ${device}
gamma: 0.99
polyak_factor: 0.005
policy_lr: 3e-4
q_lr: 3e-4
policy_frequency: 2
target_network_frequency: 1
alpha: 0.2
autotune: true
critic_hidden_dims: [256, 256]
actor_hidden_dims: [256, 256]
action_noise: "pink"
layer_norm_q: true                       # layer normalization for q-ensemble
layer_norm_a: true                       # layer normalization for actor-net