type: "3D"

defaults:
  - reward_func: real_robot_reward                                     # [penalty, gaussian, linear]

# STATE SPACE PARAMETERS ------------------------------------------------------
state_space_ext: "traj"
# init for state_space extensions (dependent on init pose!)
last_point_init: [0.5, 0.191, 1.03]
corresponding_path_points_init: [
  [0.5, 0.1693, 1.0334],
  [0.5, 0.1689, 1.0337],
  [0.5, 0.1685, 1.0341],
  [0.5, 0.1682, 1.0344],
  [0.5, 0.1678, 1.0347],
]
corresponding_path_dirs_init: [
  [0.0, -0.7349,  0.6782],
  [0.0, -0.7371,  0.6758],
  [0.0, -0.7393,  0.6734],
  [0.0, -0.7415,  0.6710],
  [0.0, -0.7436,  0.6686],
]
corresponding_path_ori_init: [132, 0, 0]
# ------------------------------------------------------ STATE SPACE PARAMETERS

# ACTION SPACE PARAMETERS -----------------------------------------------------
position_actions_min: [-0.003, -0.025, -0.025]         # [m]
position_actions_max: [0.003, 0.025, 0.025]            # [m]
kp_min: [450, 50, 30, 450, 450, 450]                 # [N/m, Nm/rad]
kp_max: [650, 200, 130, 650, 650, 650]              # [N/m, Nm/rad]
damping_factor_min: 0.8
damping_factor_max: 1.2
orientation_actions_min: [-5, -5, -5]            # [deg, euler_angles (xyz)] (heuristically determined)
orientation_actions_max: [5, 5, 5]               # [deg, euler_angles (xyz)] (heuristically determined)
scale_lower_bound: -1
scale_higher_bound: 1
control_mode: "pose"                                                # One of ["position", "pose"]
fixed_orientation: [0.9834471, 0.1808745, 0.0091225, -0.0057475]    # Set fixed orientation quaternion if control_mode is "position"
# ----------------------------------------------------- ACTION SPACE PARAMETERS

# TARGET PARAMETERS -----------------------------------------------------------
target_force: 5
target_vel: 0.05
# ----------------------------------------------------------- TARGET PARAMETERS

# REWARD MAIN PARAMETERS ------------------------------------------------------
min_force_for_contact: 1
reward_done: 1.0                                                    # r_reward, should be kept the same
reward_calc_c_done: 0.1                                             # c_reward, alter this for different weight of done reward
penalty_truncating: 1.0                                             # -c_trunc
arm_limit_collision_penalty: -10.0
# ------------------------------------------------------ REWARD MAIN PARAMETERS

# POLISHING SITES PARAMETERS --------------------------------------------------
dist_th: 0.03                                                       # Distance threshold to switch to next site [m]
dist_wiped: 0.01                                                    # Distance threshold for a marker to get wiped [m]
# positions and directions (directions have to be normed to 1)
sites:
  site_1:
    xpos: [0.5, 0.17, 1.0327]
    dir: [0.0, -0.7316, 0.6817]                                     
  site_2:
    xpos: [0.5, 0.12, 1.0657]
    dir: [0.0, -0.9075, 0.4201]
  site_3:
    xpos: [0.5, 0.06, 1.0843]      
    dir: [0.0, -0.9859, 0.1671]        
  site_4:
    xpos: [0.5, 0, 1.08982]
    dir: [0.0, -1.0, 0.0]
  site_5:
    xpos: [0.5, -0.06, 1.0843]
    dir: [0.0, -0.9859, -0.1671]
  site_6:
    xpos: [0.5, -0.12, 1.0657]
    dir: [0.0, -0.9075, -0.4201]
  site_7:
    xpos: [0.5, -0.17, 1.0327]
    dir: [0.0, -0.7316, -0.6817]
# -------------------------------------------------- POLISHING SITES PARAMETERS

# SAFETY PARAMETERS -----------------------------------------------------------
pos_cap: 0.08                                            # Position cap [m]
vel_cap: 0.5                                             # Velocity cap [m/s]
force_cap: 25                                            # Force cap [N]
# ----------------------------------------------------------- SAFETY PARAMETERS
