_target_: agents.hybrid.hybrid_agent_cheq.CHEQAgent
uncertainty_min: 0.02
uncertainty_max: 0.2
uncertainty_deque: 1                              # 1 means current uncertainty of the step... higher numbers result in averaging
weight_min: 0.2
weight_warmup_max: 0.3
weight_max: 1.0
warmup_steps: 5000